"""Licence attribution shipped inside every PK3.

Not optional and not decoration. OpenStreetMap's ODbL requires a notice
"reasonably calculated to make any Person ... aware that Content was obtained
from the Database" (ODbL 1.0 s4.3), and both Environment Agency LIDAR and the
Ordnance Survey data behind postcodes.io are OGL v3, which is attribution-only
but *is* attribution-required. Every PK3 generated before this module existed
shipped 42 files and not one word of credit.

Where it goes matters as much as what it says. ODbL s4.2(d) names exactly this
fallback -- "a location ... where users would be likely to look" -- which for an
archive is a plain text file at the top level. The OSMF Attribution Guidelines
additionally have a clause for games, allowing the credit to appear on a splash
screen, in the game view, or on a credits page, so the HUD carries a short form
too and this file carries the detail.

The generated art and the source code are ours and are not covered by any of
this; only the map geometry derives from the licensed data.
"""

from __future__ import annotations

FILENAME = "ATTRIBUTION.txt"

#: The short form, for the HUD. Must stay short enough to read at a glance.
SHORT = "(c) OpenStreetMap contributors | EA LIDAR (OGL v3)"

TEMPLATE = """\
{title}
Generated by postcode2wad {version}
{tile}

This level's geometry is derived from the following sources. The generated
artwork (sky, ground flats, building facades, trees) and the generator's source
code are not derived from them.

--- OpenStreetMap ---------------------------------------------------------
Building footprints, roads, land use, coastline and barriers.

  (c) OpenStreetMap contributors
  https://www.openstreetmap.org/copyright

Licensed under the Open Database License (ODbL) v1.0:
  https://opendatacommons.org/licenses/odbl/1-0/

This level is a Produced Work under ODbL s4.5(b) -- it is made to be played,
not to be queried for the data. The OSM extract behind any tile can be
reproduced from the generator's source and the tile ID printed above, since
generation is a pure function of that ID; the raw Overpass response for each
tile is also retained by the generator's cache and available on request.

--- Environment Agency LIDAR ----------------------------------------------
1m composite DTM and DSM: ground heights, building heights, tree canopy.

  (c) Environment Agency copyright and/or database right 2022. All rights reserved.

Licensed under the Open Government Licence v3.0:
  https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/

--- Ordnance Survey / ONS / Royal Mail ------------------------------------
Postcode to national grid lookup, via postcodes.io.

  Contains OS data (c) Crown copyright and database right
  Contains Royal Mail data (c) Royal Mail copyright and database right
  Contains National Statistics data (c) Crown copyright and database right

Licensed under the Open Government Licence v3.0.

--- Freedoom ---------------------------------------------------------------
Some wall textures. Freedoom is distributed under a modified BSD licence:
  https://freedoom.github.io/
"""


def text(title: str, version: str, tile_id: str | None = None) -> str:
    return TEMPLATE.format(
        title=title,
        version=version,
        tile="Tile: " + tile_id if tile_id else "",
    )
