"""The geolocation HUD: minimap, compass, and live coordinates.

Two halves. The minimap is *baked* at generation time (`preview.render_minimap`)
because we already know the plan and redrawing 14,000 linedefs per frame in
ZScript would be absurd. The position readout has to be live, so the tile's
georeference is baked into the script instead and evaluated per frame.

The coordinate conversion is a **local linear approximation**, not a real datum
transform. Doing OSGB36 → WGS84 properly means the OSTN15 shift grid, which is
a 1.5 MB table and a bilinear interpolation — not something to reimplement in
ZScript. Over a single 400m tile the true transform is very nearly affine, so
fitting a plane to it costs four coefficients and is accurate to a few
centimetres, far below the precision anyone reads off a HUD.
"""

from __future__ import annotations

from .tiles import Tile, osgb_to_lonlat

#: Lump and graphic names.
MINIMAP = "DMMINI"
#: Must match the class name in the template, and be registered in MAPINFO.
HANDLER = "PostcodeHUD"
ZSCRIPT_LUMP = "ZSCRIPT"

#: GZDoom feature level the script is written against.
ZSCRIPT_VERSION = "4.10"


def georeference(tile: Tile) -> dict[str, float]:
    """Fit lat/lon as a linear function of tile-local map units.

    Finite differences across the whole tile rather than a tiny epsilon: the
    span is what we care about being accurate over, and differencing over 400m
    of double-precision output is far better conditioned than over 1mm.
    """
    origin_e, origin_n = tile.origin
    span = float(tile.size_m)

    lon0, lat0 = osgb_to_lonlat(origin_e, origin_n)
    lon_e, lat_e = osgb_to_lonlat(origin_e + span, origin_n)
    lon_n, lat_n = osgb_to_lonlat(origin_e, origin_n + span)

    # Per metre, then per map unit. x is easting, y is northing.
    from . import UNITS_PER_METRE

    return {
        "lat0": lat0,
        "lon0": lon0,
        "lat_per_x": (lat_e - lat0) / span / UNITS_PER_METRE,
        "lat_per_y": (lat_n - lat0) / span / UNITS_PER_METRE,
        "lon_per_x": (lon_e - lon0) / span / UNITS_PER_METRE,
        "lon_per_y": (lon_n - lon0) / span / UNITS_PER_METRE,
    }


def build_zscript(tile: Tile, place_label: str = "") -> str:
    """The ZSCRIPT lump, with this tile's georeference baked in."""
    geo = georeference(tile)
    label = place_label.replace('"', "'")

    return _TEMPLATE.format(
        version=ZSCRIPT_VERSION,
        minimap=MINIMAP,
        tile_units=float(tile.size_units),
        label=label,
        **{k: repr(v) for k, v in geo.items()},
    )


#: Notes on the awkward bits, since they are not obvious from the code:
#:
#: * `RenderOverlay` runs in UI scope. `RenderEvent` hands us ViewPos and
#:   ViewAngle precisely so we do not have to reach into play scope for them.
#: * Doom angles run anticlockwise from east. Screen "up" is the way the player
#:   is facing, so a world bearing B sits at rotation (B - facing) anticlockwise
#:   from up, which is screen offset (-sin, -cos). North is B = 90.
#: * The minimap is north-up and never rotates. A rotating minimap is harder to
#:   read and would need the texture re-sampled; the compass carries the heading
#:   instead.
_TEMPLATE = '''\
version "{version}"

// Generated by postcode2wad. The constants below are this tile's georeference:
// latitude and longitude as a linear function of map position, fitted across
// the tile. See hud.py for why a linear fit is the right call here.
class PostcodeHUD : StaticEventHandler
{{
    const TILE_UNITS  = {tile_units};
    const LAT0        = {lat0};
    const LON0        = {lon0};
    const LAT_PER_X   = {lat_per_x};
    const LAT_PER_Y   = {lat_per_y};
    const LON_PER_X   = {lon_per_x};
    const LON_PER_Y   = {lon_per_y};

    const MARGIN      = 8;
    const PANEL_FRAC  = 0.26;   // minimap edge, as a fraction of screen height
    const MIN_PANEL   = 120;

    // A ring, as a coarse polygon. The overlay API has no circle primitive.
    ui void DrawRing(double cx, double cy, double radius, Color col, int steps)
    {{
        double prevx = cx + radius, prevy = cy;
        for (int i = 1; i <= steps; i++)
        {{
            double a = 360.0 * i / steps;
            double nx = cx + cos(a) * radius;
            double ny = cy - sin(a) * radius;
            Screen.DrawLine(int(prevx), int(prevy), int(nx), int(ny), col);
            prevx = nx; prevy = ny;
        }}
    }}

    // A filled-ish arrowhead, built from lines because ZScript has no polygon
    // fill in the overlay API.
    ui void DrawArrow(double cx, double cy, double facing, double size, Color col)
    {{
        // World (cos, sin) is east/north; the map is north-up, so screen y flips.
        double fx =  cos(facing), fy = -sin(facing);
        double sx = -fy,          sy =  fx;      // perpendicular

        double tipx = cx + fx * size,        tipy = cy + fy * size;
        double lx   = cx - fx * size * 0.6 + sx * size * 0.55;
        double ly   = cy - fy * size * 0.6 + sy * size * 0.55;
        double rx   = cx - fx * size * 0.6 - sx * size * 0.55;
        double ry   = cy - fy * size * 0.6 - sy * size * 0.55;

        Screen.DrawLine(int(tipx), int(tipy), int(lx), int(ly), col);
        Screen.DrawLine(int(tipx), int(tipy), int(rx), int(ry), col);
        Screen.DrawLine(int(lx), int(ly), int(cx), int(cy), col);
        Screen.DrawLine(int(rx), int(ry), int(cx), int(cy), col);
    }}

    ui void DrawCompass(double cx, double cy, double radius, double facing)
    {{
        Color needle = Color(255, 240, 92, 92);
        DrawRing(cx, cy, radius, Color(230, 214, 218, 226), 24);

        // North, rotated into the player's frame. Up on screen is where they
        // are looking, so north sits at (90 - facing) anticlockwise from up.
        double r = 90.0 - facing;
        double nx = -sin(r), ny = -cos(r);
        Screen.DrawLine(int(cx), int(cy), int(cx + nx * radius * 0.86),
                        int(cy + ny * radius * 0.86), needle);
        Screen.DrawLine(int(cx - nx * radius * 0.5), int(cy - ny * radius * 0.5),
                        int(cx), int(cy), Color(160, 190, 195, 200));

        Screen.DrawText(smallfont, Font.CR_GOLD,
            int(cx + nx * radius * 1.32) - smallfont.StringWidth("N") / 2,
            int(cy + ny * radius * 1.32) - smallfont.GetHeight() / 2, "N");
    }}

    override void RenderOverlay(RenderEvent e)
    {{
        if (automapactive) return;

        TextureID map = TexMan.CheckForTexture("{minimap}", TexMan.Type_Any);
        if (!map.IsValid()) return;

        int sh = Screen.GetHeight();
        int panel = int(sh * PANEL_FRAC);
        if (panel < MIN_PANEL) panel = MIN_PANEL;

        int px = MARGIN;
        int py = MARGIN;
        double cx = px + panel * 0.5;
        double cy = py + panel * 0.5;
        double radius = panel * 0.5;

        // The disc is masked into the texture's alpha, so this draws round.
        Screen.DrawTexture(map, false, px, py,
            DTA_DestWidth, panel, DTA_DestHeight, panel,
            DTA_Alpha, 0.86);
        DrawRing(cx, cy, radius - 1, Color(220, 16, 18, 22), 48);
        DrawRing(cx, cy, radius - 2, Color(150, 210, 214, 220), 48);

        // Where we are, as a fraction of the tile. The minimap is north-up and
        // covers the tile exactly, so this is a straight scale.
        double fx = e.ViewPos.X / TILE_UNITS;
        double fy = e.ViewPos.Y / TILE_UNITS;
        if (fx >= 0.0 && fx <= 1.0 && fy >= 0.0 && fy <= 1.0)
        {{
            DrawArrow(px + fx * panel, py + (1.0 - fy) * panel,
                      e.ViewAngle, panel * 0.05, Color(255, 255, 80, 96));
        }}

        double lat = LAT0 + LAT_PER_X * e.ViewPos.X + LAT_PER_Y * e.ViewPos.Y;
        double lon = LON0 + LON_PER_X * e.ViewPos.X + LON_PER_Y * e.ViewPos.Y;

        // N/S and E/W rather than a minus sign: nobody reads "-0.31" as "west"
        // at a glance.
        String coords = String.Format("%.5f%s  %.5f%s",
            abs(lat), lat >= 0 ? "N" : "S",
            abs(lon), lon >= 0 ? "E" : "W");
        String label = "{label}";

        int fh = smallfont.GetHeight();
        double crad = panel * 0.13;

        // Everything below the disc gets a dark plate behind it. Without one the
        // compass and the readout are thin light lines over a bright daylight
        // scene, and simply cannot be read — which is how the first version came
        // out.
        int blockTop = py + panel + 3;
        int blockH = int(crad * 2 + 10 + fh + 4 + (label.Length() > 0 ? fh + 2 : 0));
        Screen.Dim(0x0C1014, 0.55, px, blockTop, panel, blockH);

        double ccy = blockTop + 5 + crad;
        DrawCompass(cx, ccy, crad, e.ViewAngle);

        int ty = int(ccy + crad + 6);
        Screen.DrawText(smallfont, Font.CR_WHITE,
            int(cx) - smallfont.StringWidth(coords) / 2, ty, coords);

        if (label.Length() > 0)
        {{
            Screen.DrawText(smallfont, Font.CR_SAPPHIRE,
                int(cx) - smallfont.StringWidth(label) / 2,
                ty + fh + 2, label);
        }}
    }}
}}
'''
