"""Texture and flat names, and the OSM tags that choose between them.

Two sources. Anything beginning `DM` is ours, generated by `art.py` and shipped
inside the PK3; everything else comes from freedoom2.wad 0.13.0. The Freedoom
names were picked by looking at the rendered images rather than by assuming a
Doom 2 name still means what it used to — Freedoom reuses the lump names for
compatibility but the artwork behind them is completely different. Those are
checked in CI-ish fashion by scripts/lumps.py --check.

The ground moved to generated flats because Freedoom has essentially one green
and one grey, and neither is a British field.
"""

from __future__ import annotations

SKY_FLAT = "F_SKY1"  # special: makes a ceiling render as sky

# Ground flats. These are ours, generated by art.py and shipped in the PK3 under
# flats/ — Freedoom has one green and one grey and neither is a British field.
GRASS = "DMGRASS"
GARDEN = "DMGARDEN"  # mown; what a village looks like next to a field
MEADOW = "DMMEADOW"
PITCH = "DMPITCH"  # mown, with mower stripes
WOODLAND = "DMWOOD"
SCRUB = "DMSCRUB"
FARMLAND = "DMFARM"  # ploughed, with furrows
SAND = "DMSAND"
ROAD = "DMTARMAC"
PAVEMENT = "DMPAVE"  # slabs
CONCRETE = "DMCONC"
GRAVEL = "DMGRAVEL"
WATER = "DMWATER"

ROOF = "CEIL5_2"  # still Freedoom's; you rarely see one from eye level

# Wall textures (TEXTURE1) — legal in texturemiddle/texturetop/texturebottom.
BRICK = "BRICK1"  # tan/brown brick
BRICK_GREY = "A-BRICK1"
BRICK_DARK = "BRICK5"
STONE = "STONE2"
KERB = "STONE2"

#: The cut face of a terrain contour step.
#:
#: This was A-MUD, which drew every 0.5m contour as a brown band and turned a
#: gently sloping field into a visible flight of stairs — the single most
#: artificial thing in frame after the sky. Painting the risers with the same
#: flat as the ground they interrupt makes them read as folds in the grass
#: instead. It does not fix the staircase (that needs slopes, see the brief's
#: research item 7) but it stops it announcing itself.
#:
#: ZDoom permits a flat as a wall texture, which vanilla Doom does not.
TERRAIN_SIDE = GRASS
#: Water's edge is a genuine cut bank, so it keeps an earth face.
BANK = "A-MUD"

#: Texture repeats per default tiling, by wall texture name.
#:
#: Doom maps one texture pixel to one map unit, so a 128px-tall texture covers
#: 4m of wall. Freedoom's BRICK1 shows about ten courses over that, i.e. 40cm
#: bricks — three times life size. Nobody consciously notices, but it is why the
#: M1 screenshots read as "corridor wall" rather than "house": brick course
#: height is one of the few absolute size references a viewer has outdoors.
#:
#: Irregular textures (mud, rubble) are left alone — they have no feature size
#: to be wrong about, and scaling them just makes them noisier.
WALL_SCALE = {
    BRICK: 3.0,
    BRICK_GREY: 3.0,
    BRICK_DARK: 3.0,
    STONE: 2.0,
}


def wall_scale(name: str) -> float:
    return WALL_SCALE.get(name, 1.0)


#: Wall texture per OSM building class, so a church doesn't look like a shed.
BUILDING_WALLS = {
    "church": STONE,
    "cathedral": STONE,
    "chapel": STONE,
    "industrial": BRICK_GREY,
    "warehouse": BRICK_GREY,
    "commercial": BRICK_GREY,
    "retail": BRICK_GREY,
    "garage": BRICK_DARK,
    "garages": BRICK_DARK,
    "shed": BRICK_DARK,
}


def building_wall(tags: dict[str, str]) -> str:
    kind = tags.get("building", "yes")
    if kind in BUILDING_WALLS:
        return BUILDING_WALLS[kind]
    if tags.get("amenity") == "place_of_worship" or tags.get("historic"):
        return STONE
    return BRICK


#: Ground cover by OSM `landuse` / `leisure` / `natural` value.
#:
#: These tags were already being fetched and then thrown away, which is why
#: every tile came out uniformly green from edge to edge regardless of whether
#: it was a housing estate, an airfield or a ploughed field. Kent is mostly
#: farmland, so `farmland` and `meadow` do most of the work here.
LAND_COVER = {
    # landuse
    "farmland": FARMLAND,
    "farmyard": GRAVEL,
    "meadow": MEADOW,
    "grass": GRASS,
    "village_green": GARDEN,
    "recreation_ground": PITCH,
    "orchard": WOODLAND,
    "vineyard": FARMLAND,
    "allotments": FARMLAND,
    "forest": WOODLAND,
    "residential": GARDEN,
    "cemetery": GARDEN,
    "industrial": CONCRETE,
    "commercial": CONCRETE,
    "retail": CONCRETE,
    "quarry": GRAVEL,
    "brownfield": SCRUB,
    "greenfield": MEADOW,
    "construction": GRAVEL,
    "railway": GRAVEL,
    "military": CONCRETE,
    # leisure
    "park": GRASS,
    "garden": GARDEN,
    "flowerbed": GARDEN,
    "pitch": PITCH,
    "golf_course": PITCH,
    "playground": GRAVEL,
    "sports_centre": PITCH,
    "nature_reserve": SCRUB,
    "common": MEADOW,
    # natural
    "wood": WOODLAND,
    "scrub": SCRUB,
    "heath": SCRUB,
    "grassland": MEADOW,
    "sand": SAND,
    "beach": SAND,
    "shingle": GRAVEL,
    "bare_rock": GRAVEL,
}

def land_cover(tags: dict[str, str]) -> str | None:
    """The flat for a landuse/leisure/natural parcel, or None to leave it alone.

    Returning None matters: an untagged or unrecognised parcel must fall through
    to the terrain underneath rather than being painted a default green, or the
    feature is worse than useless — it would overwrite genuinely varied ground
    with a flat guess.
    """
    for key in ("leisure", "landuse", "natural"):
        value = tags.get(key)
        if value and value in LAND_COVER:
            return LAND_COVER[value]
    # A car park is tagged amenity, not landuse, and is far too common to miss.
    if tags.get("amenity") == "parking":
        return ROAD
    return None
