"""Texture and flat names, and the OSM tags that choose between them.

Two sources. Anything beginning `DM` is ours, generated by `art.py` and shipped
inside the PK3; everything else comes from freedoom2.wad 0.13.0. The Freedoom
names were picked by looking at the rendered images rather than by assuming a
Doom 2 name still means what it used to — Freedoom reuses the lump names for
compatibility but the artwork behind them is completely different. Those are
checked in CI-ish fashion by scripts/lumps.py --check.

The ground moved to generated flats because Freedoom has essentially one green
and one grey, and neither is a British field.
"""

from __future__ import annotations

from . import UNITS_PER_METRE
from .art import FENCE, HEDGE, MAX_STOREYS, STOREY_M, STOREY_PX, facade_name

SKY_FLAT = "F_SKY1"  # special: makes a ceiling render as sky

# Ground flats. These are ours, generated by art.py and shipped in the PK3 under
# flats/ — Freedoom has one green and one grey and neither is a British field.
GRASS = "DMGRASS"
GARDEN = "DMGARDEN"  # mown; what a village looks like next to a field
MEADOW = "DMMEADOW"
PITCH = "DMPITCH"  # mown, with mower stripes
WOODLAND = "DMWOOD"
SCRUB = "DMSCRUB"
FARMLAND = "DMFARM"  # ploughed, with furrows
SAND = "DMSAND"
ROAD = "DMTARMAC"
PAVEMENT = "DMPAVE"  # slabs
CONCRETE = "DMCONC"
GRAVEL = "DMGRAVEL"
WATER = "DMWATER"
CHALK = "DMCHALK"
MARSH = "DMMARSH"
BALLAST = "DMRAIL"
#: The rail head itself — polished steel, drawn as its own thin sector.
RAIL_HEAD = "DMRAILH"
#: Seen from above, a clipped hedge is just dense foliage, and a wall coping is
#: concrete — but both get their own flat names so a barrier top can be told
#: apart from ground wearing the same texture. See the note in art.py.
HEDGE_TOP = "DMHEDGT"
WALL_CAP = "DMWALLC"
#: Every flat that means "the top of a barrier", for tests that must not count
#: one as ground.
BARRIER_TOPS = frozenset({HEDGE_TOP, WALL_CAP})

ROOF = "CEIL5_2"  # still Freedoom's; you rarely see one from eye level

#: Everything that legitimately stands above the ground beside it. A spire
#: check that counts these finds thousands of correct answers and hides the
#: wrong ones — which the smoke test's docstring records happening once with
#: hedges alone.
STANDS_PROUD = frozenset({HEDGE_TOP, WALL_CAP, ROOF, "DMBRIDG"})

# Wall textures (TEXTURE1) — legal in texturemiddle/texturetop/texturebottom.
BRICK = "BRICK1"  # tan/brown brick
BRICK_GREY = "A-BRICK1"
BRICK_DARK = "BRICK5"
STONE = "STONE2"
KERB = "STONE2"

#: The cut face of a terrain contour step.
#:
#: This was A-MUD, which drew every 0.5m contour as a brown band and turned a
#: gently sloping field into a visible flight of stairs — the single most
#: artificial thing in frame after the sky. Painting the risers with the same
#: flat as the ground they interrupt makes them read as folds in the grass
#: instead. It does not fix the staircase (that needs slopes, see the brief's
#: research item 7) but it stops it announcing itself.
#:
#: ZDoom permits a flat as a wall texture, which vanilla Doom does not.
TERRAIN_SIDE = GRASS
#: Water's edge is a genuine cut bank, so it keeps an earth face.
BANK = "A-MUD"
#: The face of a bridge deck, and therefore the wall a road ends at where one
#: crosses it. Dark, so the dead end reads as an underpass mouth.
BRIDGE_FACE = "BRICK5"
#: The deck surface. Tarmac to the eye; distinct to a test.
BRIDGE_DECK = "DMBRIDG"

#: Land-cover category per ground flat, for measuring what a tile is made of.
#:
#: Only consulted for surfaces that came from *mapped* land cover. Bare terrain
#: is painted GRASS too, and it must not be counted as grassland: it means no
#: cover was recognised there, which is a statement about OSM's coverage rather
#: than about the ground. `SectorSpec.cover` defaults to "terrain" for exactly
#: that reason, and only the landuse path looks anything up here.
COVER_BY_FLAT = {
    GRASS: "grass",
    GARDEN: "grass",
    MEADOW: "grass",
    PITCH: "grass",
    WOODLAND: "wood",
    SCRUB: "wood",
    FARMLAND: "farm",
    SAND: "beach",
    WATER: "water",
    CONCRETE: "paved",
    GRAVEL: "paved",
    ROAD: "road",
    PAVEMENT: "road",
}

#: Texture repeats per default tiling, by wall texture name.
#:
#: Doom maps one texture pixel to one map unit, so a 128px-tall texture covers
#: 4m of wall. Freedoom's BRICK1 shows about ten courses over that, i.e. 40cm
#: bricks — three times life size. Nobody consciously notices, but it is why the
#: M1 screenshots read as "corridor wall" rather than "house": brick course
#: height is one of the few absolute size references a viewer has outdoors.
#:
#: Irregular textures (mud, rubble) are left alone — they have no feature size
#: to be wrong about, and scaling them just makes them noisier.
WALL_SCALE = {
    BRICK: 3.0,
    BRICK_GREY: 3.0,
    BRICK_DARK: 3.0,
    STONE: 2.0,
}


def wall_scale(name: str) -> float:
    return WALL_SCALE.get(name, 1.0)


#: Wall texture per OSM building class, so a church doesn't look like a shed.
BUILDING_WALLS = {
    "church": STONE,
    "cathedral": STONE,
    "chapel": STONE,
    "industrial": BRICK_GREY,
    "warehouse": BRICK_GREY,
    "commercial": BRICK_GREY,
    "retail": BRICK_GREY,
    "garage": BRICK_DARK,
    "garages": BRICK_DARK,
    "shed": BRICK_DARK,
}


def building_wall(tags: dict[str, str]) -> str:
    kind = tags.get("building", "yes")
    if kind in BUILDING_WALLS:
        return BUILDING_WALLS[kind]
    if tags.get("amenity") == "place_of_worship" or tags.get("historic"):
        return STONE
    return BRICK


#: Façade material by OSM building class. Anything not listed is domestic.
FACADE_KEYS = {
    "church": "S",
    "cathedral": "S",
    "chapel": "S",
    "industrial": "G",
    "warehouse": "G",
    "commercial": "G",
    "retail": "G",
    "office": "G",
    "garage": "G",
    "garages": "G",
    "shed": "G",
    "hut": "G",
    "greenhouse": "H",
    "glasshouse": "H",
    "hotel": "G",
    "apartments": "G",
    "train_station": "G",
    "university": "G",
    "supermarket": "G",
    "civic": "G",
    "public": "G",
    "sports_hall": "G",
    "stadium": "G",
    "farm_auxiliary": "G",
    "barn": "G",
    "school": "R",
    "hospital": "G",
}

#: Domestic walls rotate through red brick, Kent yellow stock and render. The
#: choice is a stable hash of the OSM id, not a random draw: a street needs to
#: vary, but the same house has to come out the same colour every time the tile
#: is generated or the golden-file determinism test is worthless.
DOMESTIC_FACADES = ("R", "Y", "R", "N", "Y")


def building_storeys(height_m: float) -> int:
    """How many storeys a measured height implies, clamped to what we generate."""
    return max(1, min(MAX_STOREYS, round(height_m / STOREY_M)))


#: Footprint above which an untagged building is not a house, in m².
#:
#: `building=yes` is the second largest category by area on a Sevenoaks column —
#: 9,478 m² across 41 buildings — and it carries no clue about what it is. Most
#: are houses and should stay houses, but a few are sheds and units that someone
#: never tagged, and giving those sash windows and a front door is exactly the
#: complaint that started this. Size is the signal already in hand: a detached
#: house is ~100 m² and a semi half that, so anything four times a large house
#: is not one. Deliberately generous — a wrong industrial façade on a big house
#: is worse than a domestic one on a small unit, so the threshold errs high.
BIG_FOOTPRINT_M2 = 400.0

#: Height above which a building gets the curtain wall whatever it is tagged.
#:
#: 20m is about six storeys — above a Victorian terrace and every domestic form
#: in the country, and below nothing that matters. The LIDAR measures these
#: correctly (the height is real, from DSM−DTM); it was only the drawing that
#: could not take it.
TALL_M = 20.0


def building_facade(
    tags: dict[str, str], osm_id: int, height_m: float, footprint_m2: float = 0.0
) -> tuple[str, float]:
    """The façade texture for a building, and the scaley that fits it to the wall.

    The texture is drawn to cover the whole wall exactly once, top to bottom, so
    the eaves land on the roofline and the ground floor on the ground. Doom maps
    one texture pixel to one map unit and scales by division, so covering H units
    with a T-pixel texture needs scaley = T / H.
    """
    kind = tags.get("building", "yes")
    key = FACADE_KEYS.get(kind)
    if key is None:
        if tags.get("amenity") == "place_of_worship" or tags.get("historic"):
            key = "S"
        elif kind in ("yes", "") and footprint_m2 >= BIG_FOOTPRINT_M2:
            key = "G"  # untagged and far too big to be a house — see above
        else:
            key = DOMESTIC_FACADES[osm_id % len(DOMESTIC_FACADES)]

    # Height overrides the tag. Whatever a 40m building is tagged as, it is not
    # a house, and stretching a four-storey façade over it makes each window
    # taller than a bus. Anything above TALL_M gets the curtain wall.
    if height_m >= TALL_M and key not in ("H",):
        key = "T"

    storeys = building_storeys(height_m)
    wall_units = max(1.0, height_m * UNITS_PER_METRE)
    if key == "T":
        # Tile, do not stretch: one texture-storey per real storey, repeating up
        # the wall. Doom scales a wall texture by division, so a scaley of
        # STOREY_PX per storey-worth of units repeats it exactly once per floor
        # however tall the building is.
        return facade_name(key, storeys), STOREY_PX / (STOREY_M * UNITS_PER_METRE)
    return facade_name(key, storeys), (storeys * STOREY_PX) / wall_units


#: Wall texture for a barrier. Hedge and fence are generated (art.py); masonry
#: reuses the building brick, since a garden wall is built of exactly that.
BARRIER_WALLS = {
    "hedge": HEDGE,
    "hedge_bank": HEDGE,
    "fence": FENCE,
    "guard_rail": FENCE,
    "handrail": FENCE,
    "wall": BRICK,
    "city_wall": STONE,
    "dry_stone_wall": STONE,
    "retaining_wall": STONE,
}


def barrier_wall(tags: dict[str, str]) -> str:
    return BARRIER_WALLS.get(tags.get("barrier", ""), FENCE)


#: Ground cover by OSM `landuse` / `leisure` / `natural` value.
#:
#: These tags were already being fetched and then thrown away, which is why
#: every tile came out uniformly green from edge to edge regardless of whether
#: it was a housing estate, an airfield or a ploughed field. Kent is mostly
#: farmland, so `farmland` and `meadow` do most of the work here.
LAND_COVER = {
    # landuse
    "farmland": FARMLAND,
    "farmyard": GRAVEL,
    "meadow": MEADOW,
    "grass": GRASS,
    "village_green": GARDEN,
    "recreation_ground": PITCH,
    "orchard": WOODLAND,
    "vineyard": FARMLAND,
    "allotments": FARMLAND,
    "forest": WOODLAND,
    "residential": GARDEN,
    "cemetery": GARDEN,
    "industrial": CONCRETE,
    "commercial": CONCRETE,
    "retail": CONCRETE,
    "quarry": GRAVEL,
    "brownfield": SCRUB,
    "greenfield": MEADOW,
    "construction": GRAVEL,
    "railway": GRAVEL,
    "military": CONCRETE,
    # leisure
    "park": GRASS,
    "garden": GARDEN,
    "flowerbed": GARDEN,
    "pitch": PITCH,
    "golf_course": PITCH,
    "playground": GRAVEL,
    "sports_centre": PITCH,
    "nature_reserve": SCRUB,
    "common": MEADOW,
    # natural
    "wood": WOODLAND,
    "scrub": SCRUB,
    "heath": SCRUB,
    "grassland": MEADOW,
    "sand": SAND,
    "beach": SAND,
    "shingle": GRAVEL,
    "bare_rock": GRAVEL,
    # Added 5 Aug after auditing which tags actually fall through. Sampled 36
    # tiles across Thanet and Sevenoaks: 639 parcels recognised, 34 not. These
    # are every miss that occurred more than once, plus the ones that are
    # plainly wrong when they do occur.
    #
    # swimming_pool was the single most common miss (20 of the 34) and it is
    # *water* — every pool in both districts was rendering as bare terrain,
    # which is to say as the field around it.
    "swimming_pool": WATER,
    "swimming_area": WATER,
    "wetland": MARSH,
    "marsh": MARSH,
    "dune": SAND,
    "cliff": CHALK,  # in Kent it is chalk; elsewhere it at least reads as rock
    "scree": GRAVEL,
    "horse_riding": MEADOW,
    "schoolyard": CONCRETE,
    "outdoor_seating": CONCRETE,
    "dog_park": GRASS,
    "resort": GARDEN,
    "religious": GARDEN,  # churchyards, which are mown and walled like gardens
    "plant_nursery": FARMLAND,
    "greenhouse_horticulture": FARMLAND,
    "aquaculture": WATER,
    "basin": WATER,
    "reservoir": WATER,
    "salt_pond": WATER,
}


def land_cover(tags: dict[str, str]) -> str | None:
    """The flat for a landuse/leisure/natural parcel, or None to leave it alone.

    Returning None matters: an untagged or unrecognised parcel must fall through
    to the terrain underneath rather than being painted a default green, or the
    feature is worse than useless — it would overwrite genuinely varied ground
    with a flat guess.
    """
    for key in ("leisure", "landuse", "natural"):
        value = tags.get(key)
        if value and value in LAND_COVER:
            return LAND_COVER[value]
    # A car park is tagged amenity, not landuse, and is far too common to miss.
    if tags.get("amenity") == "parking":
        return ROAD
    return None
